services:

  api:
    image: vrangrops/sparta-test-app:latest
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tictactoe
      - STATEFUL_MODE=mongodb
    # Seed FIRST, then launch the server
    command: /bin/sh -c "node seeds/seed.js; node index.js"
    depends_on:
      - mongodb

  # The MongoDB Database
  mongodb:
    image: mongo:8.2.5
    ports:
      - "27017:27017"
    volumes:
      - ttt-mongodb-data:/data/db

volumes:
  ttt-mongodb-data: