server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://sparta-node-app:3000; # Change 3000 to your Node port
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
